# Stage 1: Build
FROM node:20 AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

COPY . .
RUN rm -rf node_modules/.cache && \
    rm -rf node_modules/.vite && \
    ./node_modules/.bin/ng build shared-utils && \
    ./node_modules/.bin/ng build seis-mfe-gestion-usuario --configuration development --base-href=/mfe-gestion-usuario/

# Stage 2: Nginx
FROM nginx:alpine

RUN rm -rf /etc/nginx/conf.d/default.conf
COPY nginx.mfe-gestion-usuario.conf /etc/nginx/nginx.conf

COPY --from=builder /app/dist/seis-mfe-gestion-usuario/browser /usr/share/nginx/html

RUN chmod -R 755 /usr/share/nginx/html && \
    chown -R nginx:nginx /usr/share/nginx/html

RUN nginx -t

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://localhost/ || exit 1

CMD ["nginx", "-g", "daemon off;"]
